export const UPDATE_CARD_SHIPPING_ADDRESS = 'app/UserPage/UPDATE_CARD_SHIPPING_ADDRESS';
export const UPDATE_CARD_SHIPPING_ADDRESS_SUCCESS = 'app/UserPage/UPDATE_CARD_SHIPPING_ADDRESS_SUCCESS';
export const UPDATE_CARD_SHIPPING_ADDRESS_ERROR = 'app/UserPage/UPDATE_CARD_SHIPPING_ADDRESS_ERROR';
