export const LOAD_CARD_DETAILS = 'app/CardDetailsPage/LOAD_CARD_DETAILS';
export const LOAD_CARD_DETAILS_SUCCESS = 'app/CardDetailsPage/LOAD_CARD_DETAILS_SUCCESS';
export const LOAD_CARD_DETAILS_ERROR = 'app/CardDetailsPage/LOAD_CARD_DETAILS_ERROR';

export const UPDATE_CARD_INFORMATION = 'app/CardDetailsPage/UPDATE_CARD_INFORMATION';
export const UPDATE_CARD_INFORMATION_SUCCESS = 'app/CardDetailsPage/UPDATE_CARD_INFORMATION_SUCCESS';
export const UPDATE_CARD_INFORMATION_ERROR = 'app/CardDetailsPage/UPDATE_CARD_INFORMATION_ERROR';

export const REISSUE_CARD = 'app/CardDetailsPage/REISSUE_CARD';
export const REISSUE_CARD_SUCCESS = 'app/CardDetailsPage/REISSUE_CARD_SUCCESS';
export const REISSUE_CARD_ERROR = 'app/CardDetailsPage/REISSUE_CARD_ERROR';

export const DELETE_CARD = 'app/CardDetailsPage/DELETE_CARD';
export const DELETE_CARD_SUCCESS = 'app/CardDetailsPage/DELETE_CARD_SUCCESS';
export const DELETE_CARD_ERROR = 'app/CardDetailsPage/DELETE_CARD_ERROR';

export const LOAD_TRANSACTION_HISTORY = 'bento/CardDetailsPage/LOAD_TRANSACTION_HISTORY';
export const LOAD_TRANSACTION_HISTORY_SUCCESS = 'bento/CardDetailsPage/LOAD_TRANSACTION_HISTORY_SUCCESS';
export const LOAD_TRANSACTION_HISTORY_ERROR = 'bento/CardDetailsPage/LOAD_TRANSACTION_HISTORY_ERROR';
