export const SET_INITIATE_CREDIT_DEBIT = 'app/UserPage/SET_INITIATE_CREDIT_DEBIT';
export const SET_INITIATE_CREDIT_DEBIT_SUCCESS = 'app/UserPage/SET_INITIATE_CREDIT_DEBIT_SUCCESS';
export const SET_INITIATE_CREDIT_DEBIT_ERROR = 'app/UserPage/SET_INITIATE_CREDIT_DEBIT_ERROR';
