export const NO_NOTE_SELECTED = -1;

export const CREATE_NEW_BUSINESS_NOTE = 'app/UserPage/CREATE_NEW_BUSINESS_NOTE';
export const CREATE_NEW_BUSINESS_NOTE_SUCCESS = 'app/UserPage/CREATE_NEW_BUSINESS_NOTE_SUCCESS';
export const CREATE_NEW_BUSINESS_NOTE_ERROR = 'app/UserPage/CREATE_NEW_BUSINESS_NOTE_ERROR';
export const DELETE_BUSINESS_NOTE = 'app/UserPage/DELETE_BUSINESS_NOTE';
export const DELETE_BUSINESS_NOTE_SUCCESS = 'app/UserPage/DELETE_BUSINESS_NOTE_SUCCESS';
export const DELETE_BUSINESS_NOTE_ERROR = 'app/UserPage/DELETE_BUSINESS_NOTE_ERROR';
export const EDIT_BUSINESS_NOTE = 'app/UserPage/EDIT_BUSINESS_NOTE';
export const EDIT_BUSINESS_NOTE_SUCCESS = 'app/UserPage/EDIT_BUSINESS_NOTE_SUCCESS';
export const EDIT_BUSINESS_NOTE_ERROR = 'app/UserPage/EDIT_BUSINESS_NOTE_ERROR';
export const EDIT_BUSINESS_SELECTED_NOTE_TO_EDIT = 'app/UserPage/EDIT_BUSINESS_SELECTED_NOTE_TO_EDIT';
