export const UPDATE_BUSINESS_INFO = 'app/UserPage/UPDATE_BUSINESS_INFO';
export const UPDATE_BUSINESS_INFO_SUCCESS = 'app/UserPage/UPDATE_BUSINESS_INFO_SUCCESS';
export const UPDATE_BUSINESS_INFO_ERROR = 'app/UserPage/UPDATE_BUSINESS_INFO_ERROR';

export const COUNTRY = 'USA';
