export const GET_BUSINESS_CLASSIFICATION = 'app/UserPage/GET_BUSINESS_CLASSIFICATION';
export const GET_BUSINESS_CLASSIFICATION_SUCCESS = 'app/UserPage/GET_BUSINESS_CLASSIFICATION_SUCCESS';
export const GET_BUSINESS_CLASSIFICATION_ERROR = 'app/UserPage/GET_BUSINESS_CLASSIFICATION_ERROR';
export const UPDATE_BUSINESS_CLASSIFICATION = 'app/UserPage/UPDATE_BUSINESS_CLASSIFICATION';
export const UPDATE_BUSINESS_CLASSIFICATION_SUCCESS = 'app/UserPage/UPDATE_BUSINESS_CLASSIFICATION_SUCCESS';
export const UPDATE_BUSINESS_CLASSIFICATION_ERROR = 'app/UserPage/UPDATE_BUSINESS_CLASSIFICATION_ERROR';
