export const UPDATE_BANKING_SUBSCRIPTION_PLAN = 'app/UserPage/UPDATE_BANKING_SUBSCRIPTION_PLAN';
export const UPDATE_BANKING_SUBSCRIPTION_PLAN_SUCCESS = 'app/UserPage/UPDATE_BANKING_SUBSCRIPTION_PLAN_SUCCESS';
export const UPDATE_BANKING_SUBSCRIPTION_PLAN_ERROR = 'app/UserPage/UPDATE_BANKING_SUBSCRIPTION_PLAN_ERROR';
