export const GET_MIGRATION_INFO = 'app/UserPage/GET_MIGRATION_INFO';
export const GET_MIGRATION_INFO_SUCCESS = 'app/UserPage/GET_MIGRATION_INFO_SUCCESS';
export const GET_NEW_BUSINESS_INFO_SUCCESS = 'app/UserPage/GET_NEW_BUSINESS_INFO_SUCCESS';
export const GET_MIGRATION_INFO_ERROR = 'app/UserPage/GET_MIGRATION_INFO_ERROR';
